PUT  http://localhost:8080/change-password
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk1Mzg1OTIsInVzZXJfaWQiOjF9.OXWYY_21GQikJ_ltwpk4sHn8HpAha0wGUpxRARdNQYg



{
    "old_password":"Anu20.",
    "new_password": "Anu2020.",
    "confirm_password": "Anu2020."

}
