
POST http://localhost:8080/events
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk1Mzg1OTIsInVzZXJfaWQiOjF9.OXWYY_21GQikJ_ltwpk4sHn8HpAha0wGUpxRARdNQYg

{
    "name": "Flutterbytes Afrika",
    "description": "A flutter conference for dart people",
    "location_address": "Victoria Island",
    "location_venue": "Zonetech Park",
    "capacity":70,
    "event_date": "2025-01-01T15:30:00.000Z"
 
}   