
POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxM0BleGFtcGxlLmNvbSIsImV4cCI6MTcyOTkxOTcxOCwidXNlcklkIjoxfQ.6NTqL7ewciiRz5NipmQTuPKFBCTvdWPVKioruAjzHgM

{
    "name": "Test4 eventss",
    "description": "A test4 eventss",
    "location": "A test4 location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}