DELETE http://localhost:8070/events/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk1Mzg1OTIsInVzZXJfaWQiOjF9.OXWYY_21GQikJ_ltwpk4sHn8HpAha0wGUpxRARdNQYg
