GET http://localhost:8070/events/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk2Mzc2OTQsInVzZXJfaWQiOjF9.AtGaH7vPH1Xag9zYWWnOB6KW0Tu1ElVYg95VbqxQ2Dg