
PUT http://localhost:8080/events/5
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q5QGV4YW1wbGUuY29tIiwiZXhwIjoxNzI5NTc4ODUxLCJ1c2VySWQiOjN9.2gZ8qU25VpdkjZppFukFtIxnvJFIRoAYXnEmL6Ydszc

{
    "name": "Updated test events2",
    "description": "An updated test events",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00Z"
}