
PUT http://localhost:8080/events/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk1Mzg1OTIsInVzZXJfaWQiOjF9.OXWYY_21GQikJ_ltwpk4sHn8HpAha0wGUpxRARdNQYg

{
    "name": "Stella Afrika",
    "description": "A web conference for web3 people",
    "location_address": "Lekii",
    "location_venue": "Zonetech Parkss",
    "capacity":60,
    "event_date": "2025-01-01T15:30:00.000Z"
 
}   